### ISSUE TITLE
Question in homo_warping function

### ISSUE THREAD

**Issue by JiangQi715** [kwea123/MVSNet_pl#3]
In the home warming function, the normalized result after coordinate transformation may not be between - 1 and 1, because the coordinate change may make x greater than width - 1, y greater than height - 1. How do you understand this? I look forward to your reply, thank you.

**Comment by kwea123** [comment]
If it's not between -1 and 1 it means that pixel is warped outside of the image, in that case that pixel has value 0 (all black) which is specified by padding_mode='zeros'
